### ISSUE TITLE
Method of Morris: Tools

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#58]
I've a shopping list of little utilities and tools which I'd like to add to the Method of Morris.

**Utilities**
- Remove simulation/missing data from results, and recompute metrics - this is inspired by a paper from [Branger et al. (2015)](http://linkinghub.elsevier.com/retrieve/pii/S1364815215001097) who note that a piece of missing data affects only the computation of two elementary effects.  These can just be removed from the input sample and model results.  However, this will result in irregularly sized trajectories, so will need to bypass the checks on sample and trajectory size related to the number of parameters.
- Input sample analysis - a quick utility which returns the histograms of each input parameter for a given input sample, with the option to view either the levels (e.g. 1,2,3 or 4) or sample values (e.g. -0.5, 0, 0.5, 1)
- Input sample analysis - a utility which identifies which input changed in which simulation (for identifying which input parameter caused a crash or infeasible solution) - could also identify the previous and next levels for each parameter

**Visualisations**
This is potentially a no-go zone because it would add a dependency to [Matplotlib](http://matplotlib.org), but this is such a ubiquitous package it may not be an issue.  The aesthetics also quickly get subjective (I prefer [seaborn](https://github.com/mwaskom/seaborn) for example)...

**Results**
- Scatter plot of mu\* versus sigma
  ![results_mu_star_conf_v44_l8_gs4_k20_n100_241214170137](https://cloud.githubusercontent.com/assets/3727919/8210693/124cc142-150b-11e5-9147-e85b703f7aa2.png)
- Scatter plot of mu versus sigma
- Horizontal bar chart of mu\* with sigma as error bars
- Horizontal bar chart of mu with sigma as error bars

**Utilities**
- Histogram of selected parameter/s for a given input sample
- Matrix plot of entire input sample, with groups sharing colours, and levels shown as different shading
  ![posterbackground_png](https://cloud.githubusercontent.com/assets/3727919/8210625/cf626652-150a-11e5-86b7-83fe0433e920.png)

**Comment by dojeda** [comment]
+1 on this one... I am only discovering this module, but I use a lot of Morris and Sobol indices in my research. The most useful plots to me are the  mu/sigma, mu*/sigma (both with the mu=sigma reference line), and also a horizontal barchart with the effects ordered by the Eucidean distance of the (mu,sigma) points (with respect to the origin).
The other ubiquitous plot of my research is the Sobol main/total effect indices with confidence intervals.

I do most of my sensitivity analyses with the `sensitivity` package of R, but I'm always looking for python alternatives.  I'll try to come up with a PR if I have the time this weekend

**Comment by willu47** [comment]
Thanks a lot for the comments.  A pull-request would be great.  I've a bunch of boiler plate code lying around for generating many of these plots, so an excuse to formalise it and share it in the library would be great.  I'm intrigued by the Euclidean distance bar chart.

I've focussed mainly on Morris, as this is predominantly what I use, so contributions for the other methods would be invaluable.

One question is how to write tests for these?

**Comment by dojeda** [comment]
Regarding the Euclidean distance bar chart : I'll shamelessly leave this link to a publication where we used it to identify important parameters : http://www.ncbi.nlm.nih.gov/pubmed/24658245
There are a couple of papers that use this method for the same purpose, ignoring the linear, non-linear or interactive information that Morris suggests by the placement of the effects in the mu-sigma plane.

`One question is how to write tests for these?`
I'm not sure if you are asking about the tests of the plots or for the sensitivity analysis methods.

Concerning the SA methods:

In my opinion, the question of testing these methods is extremely important. I imagine that you already have given a lot of thought to this.

Two ideas:
1 . Use the classic testbed functions or custom functions that have analytic values for their indices. For example, Saltelli in his book *Global Sensitivity Analysis, The Primer* provides the exact Sobol indices main and total order of the Ishigami function, if I recall correctly. I haven't read your test suites, but I would probably compare the Sobol estimations with these real values and fail if they are not within a certain tolerance.
2. I met some of the developers of R's `sensitivity` package. I think their implementations are correct and they have a big user base that has helped them to refine their code. My suggestion would be to test against their implementations with the same functions. 

Concerning the plot methods:
The only idea that comes to mind is that matplotlib returns a list of artist objects with each plot. I believe one can programmatically assert that the plot is correct without using the graphical interface (e.g. plot to a PNG file, obtain artists, check that the artists are consistent with the intended result).

**Comment by dojeda** [comment]
Forgot to comment on:
* Histogram of selected parameter/s for a given input sample
This one is very important to me as well.. as it tells me if my "step" parameter of the Morris method is correct or not, even before doing all my function evaluations.

* Matrix plot of entire input sample, with groups sharing colours, and levels shown as different shading 
I'm not sure how this one is useful, can you comment on how you use this kind of diagram?

**Comment by willu47** [comment]
* I was wondering how to test the plots - and you've suggested a neat solution.
* Testing for Morris is relatively good, less so for the other methods.  I've used the examples in the Saltelli book.  We've implemented test functions - the G-Sobol and Ishigami functions, which allow analytical solutions to be compared with estimated sensitivity indices.  Still a little way to go on the latter too.
* I use the matrix plot of the sample for presentation purposes - it's useful to explain how the sample changes, and the relationship between levels, trajectories, parameters, groups and simulations

Another question:
* Have you used the scaled elementary-effects outlined in [Sin et al (2009)](http://www.sciencedirect.com/science/article/pii/S1570794609701543)?

Sin, Gürkan, and Krist V. Gernaey. “Improving the Morris Method for Sensitivity Analysis by Scaling the Elementary Effects.” Computer Aided Chemical Engineering 26 (2009): 925–930. doi:10.1016/S1570-7946(09)70154-3.

**Comment by dojeda** [comment]
Hello Will,
This is a nice discussion. I am still having some trouble understanding the third point. Perhaps it is because I've never used the grouped version of the Morris method.

Concerning Sin's paper. Very interesting. If I understand correctly, he is tackling the problem of having parameters with very different ranges. However, I don't exactly understand the logic and correctness of using the standard deviation of the output and the factors. I wish he had used a toy/simple function to demonstrate his point.

I already have had problems when my parameter space is very different among dimensions, i.e. a parameter within [0,10] and another one in [1e5,1e6]. Or sometimes when parameter P1 is in [0,1] and P2 in [0,5], which is not that different, but the larger range of P2 biases its importance.
I believe the main problem is that Morris defined \lambda in [0,1], which is rarely the case for any model unless the parameters have been normalized.

I have lost so much sleep over this problem. Sometimes I feel that I should normalize my factors, sometimes I feel I am biasing my results when doing it. Additionally, the R function that handles this does not follow the paper description and it had led me many times to err.

I even wrote this in one of my scripts:
```
###############################################################################
# NOTES:
# [1] Dear me from the future or the person that uses this code:
# I know that there is a 'scale' parameter in the morris function. I have lost
# many days in my life wondering if the delta should be scaled or not.
# There is a serious problem because the literature says one thing and the
# R code does another.
# IN SHORT: THE SCALE PARAMETER SHOULD BE TRUE !!!!! TRUST ME
# To clarify, read page 120 of Saltelli's Primer. Saltelli says that one should
# not scale. This implies that if a model is y=X1+X2 with X1~U(0,1) and
# X2~U(0,10), the X2 parameter gets higher effects, even though both parameters
# have the same importance to y. However, X2 is important because of the limits
# defined in its distribution. So put scale=true in order to account for
# that. Read carefully Saltelli's comment.
# Good luck and happy analyses,
# dojeda
...
plan_morris = morris(model=NULL,
                     factors=parameter_short,
                     r=repetitions,
                     design=list(type='oat',levels=n_levels,grid.jump=jump),
                     binf=parameter_binf,
                     bsup=parameter_bsup,
                     scale=TRUE) # for scale, see notes [1]
...
```

I'm still not sure which is the right way to go. I trust my past self, although he has been wrong before :)

**Comment by ele-b** [comment]
Hi Will

Thanks a lot for the whole package and also for this kind of discussions, it is all very useful for someone like me that has just entered the world of SA!
I have personally used only the Morris method so far and regarding the visualisation of the results, I took inspiration from my supervisor's papers and created something like this with Matplotlib:

![morris-4cm48-m-tai](https://cloud.githubusercontent.com/assets/8657652/8360641/eb29859e-1b65-11e5-8b48-9ea5c7882594.png)

The histogram of the input parameters would be also welcome, as well as a combination LHS/Morris, as the optimal trajectories calculation on my machine requires a really long time and gets impossible over 8 trajectories.

Thanks again!

**Comment by willu47** [comment]
Thanks for the plots and kind words @ele-b.  I like the [coefficient-of-variation](https://en.wikipedia.org/wiki/Coefficient_of_variation) lines you have included in the right-hand plot.  A quick question - are you sure the units for ![mustar](https://cloud.githubusercontent.com/assets/3727919/8362361/487cbbbc-1b70-11e5-827e-ac95ae4fdd51.png) are correct in the left-hand plot?  If you fancy contributing your plotting code to the library, you can submit a pull-request.

Make a new branch, add and commit your code and then submit a pull request.  In the comments of the pull request, we can then discuss the details of the code and make modifications before bringing the code into the master branch of the repository.

Generally, I think the SALib plotting procedures should return a matplotlib plot which can then be further modified before being displayed.  Everyone has such different aesthetic tastes, and I don't wish to be prescriptive.  On the other hand, we also want the new visualisation features to be useful, and quick to use when performing iterative analytical work.

**Comment by ele-b** [comment]
Of course, sorry, on the left hand plot it should be klux hr too!

I tend to change the matplotlibrc file when I want a slightly different appearance for my graphs, would it be possible to leave the aesthetic flexibility to that? 

I'm not too sure about how GitHub works, but I'll give it a try as soon as possible!

**Comment by jdherman** [comment]
Thanks Will and everyone else for discussing this. We'll be fine adding a matplotlib dependency since the  interest seems unanimous. I second Will's idea to return a plot object rather than displaying it, so we don't bury plotting preferences in the library code. Would this work as a rough API:

```python
Si = morris.analyze(problem, param_values, Y, conf_level=0.95, print_to_console=False, num_levels=10, grid_jump=5)
p = morris.cov_plot(Si)
# set plot style etc.
p.show()
```

This way the plotting code would be self-contained. It should work fine with the *.rc file, but also allow flexibility for people who don't use those (or who want to rely on seaborn defaults instead).

As an aside, I'd be interested to learn more about how these plots can be interpreted if anyone has time for a brief summary :)

**Comment by willu47** [comment]
As the above note states, I've now opened a pull request so we can discuss the actual code behind a plotting package for SALib.  Feel free to comment on the code, discuss in the pull request, and add your code ideas in the comments.  But, just don't merge it yet!

**Comment by jdherman** [comment]
Let's close this one - we have the basic plots, and additional plots we can discuss in #272 

I'll also create a separate issue to talk about handling missing data, that applies across a few different methods
